version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./backend/Saved trained model:/app/Saved trained model
        environment:
            - FLASK_ENV=development
            - FLASK_APP=/app/src/api.py
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - REACT_APP_API_URL=http://localhost:5000
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
